# Generated by Django 4.1.5 on 2023-01-22 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('ask', models.FloatField()),
                ('bid', models.FloatField()),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pair_manager.exchange')),
            ],
        ),
    ]
